# GENERATED by supabase/functions/journey/gen_billing.py -- do not edit.
# Sources: _Hub/pricing/tmh_pricing_catalogue.json, temmy-access/tmh_billing.py
CATALOGUE = {
  "AUDIT_UK": {
    "name": "UK Clearance Audit",
    "unit": "trademark",
    "rrp": 149,
    "discounted": 119,
    "baseline": 99,
    "product_code_dom": "UKTM-AUD-UK-DOM",
    "product_code_intl": "UKTM-AUD-UK-INTL"
  },
  "AUDIT_WORLDWIDE": {
    "name": "Worldwide Clearance Audit",
    "unit": "trademark",
    "rrp": 199,
    "discounted": 169,
    "baseline": 149,
    "product_code_dom": "UKTM-AUD-WW-DOM",
    "product_code_intl": "UKTM-AUD-WW-INTL"
  },
  "CONSULT_CLEARANCE": {
    "name": "Clearance Consultation",
    "unit": "consultation",
    "rrp": 149,
    "discounted": 119,
    "baseline": 99,
    "product_code_dom": "UKTM-CONS-DOM",
    "product_code_intl": "UKTM-CONS-INTL"
  }
}

BILLING_CODES = {
  "uk": "227",
  "nonuk": "247",
  "tax_uk": "OUTPUT2",
  "tax_nonuk": "NONE",
  "forbidden": [
    "608",
    "609",
    "610"
  ]
}
