"""LinkedIn industry -> SIC division(s) — the off-the-shelf industry taxonomy.

Jonathan (15 Jul): use the full ~430 LinkedIn industry list ("what people are
used to"). This is the AI-routes-to-real-data mapping: each industry maps to
its primary UK SIC 2007 division(s) (the 2-digit grain), and the empirical
engine (sic_engine + the seed) turns those into real, frequency-banded classes
and terms. The LLM never picks classes — it only maps industry -> SIC.

Grain = 2-digit division on purpose (Jonathan's "2, 3 or 4 digits, primary
SIC"): coarse enough to be off-the-shelf, and the level the empirical seed and
concordance both work at. Multiple divisions are combined by the engine.

Refine any single mapping by editing its list here — nothing else changes.
"""
from __future__ import annotations

# {LinkedIn industry name: [SIC 2007 division(s)]}
INDUSTRY_SIC: dict[str, list[str]] = {
    "Defense and Space Manufacturing": ["30", "25"],
    "Optometrists": ["86"],
    "Computer Hardware Manufacturing": ["26"],
    "Software Development": ["62"],
    "Computer Networking Products": ["26"],
    "Transportation Equipment Manufacturing": ["30", "29"],
    "Technology, Information and Internet": ["62", "63"],
    "Physical, Occupational and Speech Therapists": ["86"],
    "Semiconductor Manufacturing": ["26"],
    "Telecommunications": ["61"],
    "Law Practice": ["69"],
    "Housing Programs": ["84", "68"],
    "Legal Services": ["69"],
    "Business Consulting and Services": ["70"],
    "Biotechnology Research": ["72", "21"],
    "Family Planning Centers": ["86"],
    "Medical Practices": ["86"],
    "Transportation Programs": ["84", "49"],
    "Hospitals and Health Care": ["86"],
    "Utilities Administration": ["84", "35"],
    "Pharmaceutical Manufacturing": ["21"],
    "Outpatient Care Centers": ["86"],
    "Veterinary Services": ["75"],
    "Medical Equipment Manufacturing": ["32", "26"],
    "Space Research and Technology": ["72"],
    "Personal Care Product Manufacturing": ["20"],
    "Motor Vehicle Parts Manufacturing": ["29"],
    "Retail Apparel and Fashion": ["47", "14"],
    "Sporting Goods Manufacturing": ["32"],
    "Tobacco Manufacturing": ["12"],
    "Medical and Diagnostic Laboratories": ["86"],
    "Retail Groceries": ["47"],
    "Food and Beverage Manufacturing": ["10", "11"],
    "Oil Extraction": ["06"],
    "Computers and Electronics Manufacturing": ["26"],
    "Natural Gas Extraction": ["06"],
    "Manufacturing": ["25", "28"],
    "Furniture and Home Furnishings Manufacturing": ["31"],
    "Home Health Care Services": ["86", "88"],
    "Retail": ["47"],
    "Embedded Software Products": ["62"],
    "Entertainment Providers": ["90", "59"],
    "Mobile Computing Software Products": ["62"],
    "Gambling Facilities and Casinos": ["92"],
    "Ambulance Services": ["86"],
    "Desktop Computing Software Products": ["62"],
    "Travel Arrangements": ["79"],
    "IT System Custom Software Development": ["62"],
    "Hospitality": ["55", "56"],
    "IT System Operations and Maintenance": ["62"],
    "Restaurants": ["56"],
    "IT System Installation and Disposal": ["62"],
    "Spectator Sports": ["93"],
    "Hospitals": ["86"],
    "IT System Training and Support": ["62"],
    "Food and Beverage Services": ["56"],
    "IT System Data Services": ["63", "62"],
    "Movies, Videos, and Sound": ["59"],
    "IT System Testing and Evaluation": ["62"],
    "Broadcast Media Production and Distribution": ["60", "59"],
    "Museums, Historical Sites, and Zoos": ["91"],
    "Artists and Writers": ["90"],
    "Performing Arts": ["90"],
    "Recreational Facilities": ["93"],
    "Banking": ["64"],
    "Insurance": ["65"],
    "Financial Services": ["64", "66"],
    "Nursing Homes and Residential Care Facilities": ["87"],
    "Real Estate": ["68"],
    "Investment Banking": ["64", "66"],
    "Investment Management": ["66"],
    "Accounting": ["69"],
    "Construction": ["41", "43"],
    "Wholesale Building Materials": ["46"],
    "Architecture and Planning": ["71"],
    "Civil Engineering": ["42", "71"],
    "Aviation and Aerospace Component Manufacturing": ["30"],
    "Internet News": ["63", "58"],
    "Motor Vehicle Manufacturing": ["29"],
    "Blogs": ["63"],
    "Chemical Manufacturing": ["20"],
    "Interior Design": ["74"],
    "Machinery Manufacturing": ["28"],
    "Social Networking Platforms": ["63"],
    "Mining": ["07", "08"],
    "Household and Institutional Furniture Manufacturing": ["31"],
    "Business Intelligence Platforms": ["62"],
    "Oil and Gas": ["06"],
    "Business Content": ["63", "58"],
    "Shipbuilding": ["30"],
    "Data Security Software Products": ["62"],
    "Utilities": ["35", "36"],
    "Mobile Gaming Apps": ["62", "58"],
    "Textile Manufacturing": ["13"],
    "Internet Publishing": ["58", "63"],
    "Paper and Forest Product Manufacturing": ["17", "16"],
    "Media and Telecommunications": ["60", "61"],
    "Railroad Equipment Manufacturing": ["30"],
    "Blockchain Services": ["62"],
    "Farming": ["01"],
    "Ranching": ["01"],
    "Services for the Elderly and Disabled": ["88", "87"],
    "Dairy Product Manufacturing": ["10"],
    "Fisheries": ["03"],
    "Office Furniture and Fixtures Manufacturing": ["31"],
    "Primary and Secondary Education": ["85"],
    "Community Services": ["88"],
    "Higher Education": ["85"],
    "Education Administration Programs": ["85", "84"],
    "Research Services": ["72"],
    "Armed Forces": ["84"],
    "Mattress and Blinds Manufacturing": ["31", "13"],
    "Legislative Offices": ["84"],
    "Administration of Justice": ["84"],
    "International Affairs": ["84"],
    "Emergency and Relief Services": ["88"],
    "Government Administration": ["84"],
    "Executive Offices": ["84"],
    "Law Enforcement": ["84"],
    "Vocational Rehabilitation Services": ["88"],
    "Public Safety": ["84"],
    "Public Policy Offices": ["84"],
    "Advertising Services": ["73"],
    "Child Day Care Services": ["88"],
    "Newspaper Publishing": ["58"],
    "Book and Periodical Publishing": ["58"],
    "Performing Arts and Spectator Sports": ["90", "93"],
    "Printing Services": ["18"],
    "Information Services": ["63"],
    "Libraries": ["91"],
    "Theater Companies": ["90"],
    "Environmental Services": ["39", "38"],
    "Freight and Package Transportation": ["49", "52"],
    "Dance Companies": ["90"],
    "Individual and Family Services": ["88"],
    "Religious Institutions": ["94"],
    "Civic and Social Organizations": ["94"],
    "Consumer Services": ["96"],
    "Circuses and Magic Shows": ["90"],
    "Truck Transportation": ["49"],
    "Warehousing and Storage": ["52"],
    "Airlines and Aviation": ["51"],
    "Sports Teams and Clubs": ["93"],
    "Maritime Transportation": ["50"],
    "Racetracks": ["93", "92"],
    "IT Services and IT Consulting": ["62"],
    "Market Research": ["73"],
    "Public Relations and Communications Services": ["70", "73"],
    "Design Services": ["74"],
    "Non-profit Organizations": ["94"],
    "Fundraising": ["88", "94"],
    "Strategic Management Services": ["70"],
    "Writing and Editing": ["90", "74"],
    "Staffing and Recruiting": ["78"],
    "Wholesale Motor Vehicles and Parts": ["45"],
    "Professional Training and Coaching": ["85"],
    "Venture Capital and Private Equity Principals": ["66", "64"],
    "Political Organizations": ["94"],
    "Translation and Localization": ["74"],
    "Computer Games": ["58", "62"],
    "Events Services": ["82", "93"],
    "Retail Art Supplies": ["47"],
    "Museums": ["91"],
    "Appliances, Electrical, and Electronics Manufacturing": ["27", "26"],
    "Online Audio and Video Media": ["59", "63"],
    "Wholesale Furniture and Home Furnishings": ["46"],
    "Historical Sites": ["91"],
    "Nanotechnology Research": ["72"],
    "Retail Art Dealers": ["47"],
    "Musicians": ["90"],
    "Zoos and Botanical Gardens": ["91"],
    "Defense & Space": ["30", "84"],
    "Transportation, Logistics, Supply Chain and Storage": ["52", "49"],
    "Veterinary": ["75"],
    "Plastics Manufacturing": ["22"],
    "Cosmetics": ["20"],
    "Computer and Network Security": ["62"],
    "Apparel & Fashion": ["14", "47"],
    "Wireless Services": ["61"],
    "Amusement Parks and Arcades": ["93"],
    "Consumer Electronics": ["26", "47"],
    "Alternative Dispute Resolution": ["69"],
    "Consumer Goods": ["47"],
    "Security and Investigations": ["80"],
    "Furniture": ["31"],
    "Facilities Services": ["81"],
    "Leisure, Travel & Tourism": ["79"],
    "Outsourcing and Offshoring Consulting": ["70", "82"],
    "Food & Beverages": ["10", "56"],
    "Wellness and Fitness Services": ["96", "93"],
    "Fine Art": ["90"],
    "Alternative Medicine": ["86"],
    "Building Materials": ["23", "46"],
    "Media Production": ["59"],
    "Automotive": ["29", "45"],
    "Animation and Post-production": ["59"],
    "Dairy": ["10", "01"],
    "Leasing Non-residential Real Estate": ["68"],
    "Education Management": ["85"],
    "Capital Markets": ["66"],
    "Wholesale Photography Equipment and Supplies": ["46"],
    "Public Policy": ["84"],
    "Think Tanks": ["72", "94"],
    "Non-profit Organization Management": ["94"],
    "Philanthropic Fundraising Services": ["88"],
    "Golf Courses and Country Clubs": ["93"],
    "Program Development": ["88"],
    "E-Learning Providers": ["85"],
    "Arts & Crafts": ["32", "47"],
    "Wholesale": ["46"],
    "Wholesale Computer Equipment": ["46"],
    "Skiing Facilities": ["93"],
    "Music": ["90", "59"],
    "Social Networking/Social Media": ["63"],
    "Wholesale Import and Export": ["46"],
    "Outsourcing/Offshoring": ["82"],
    "Artificial Intelligence": ["62"],
    "Industrial Machinery Manufacturing": ["28"],
    "Health, Wellness & Fitness": ["96", "93"],
    "Photography": ["74"],
    "E-learning": ["85"],
    "Human Resources Services": ["78"],
    "Import & Export": ["46"],
    "Retail Office Equipment": ["47"],
    "Human Resources": ["78"],
    "Mental Health Care": ["86"],
    "Business Supplies & Equipment": ["46"],
    "Graphic Design": ["74"],
    "Luxury Goods & Jewelry": ["32", "47"],
    "International Trade and Development": ["46", "84"],
    "Renewables & Environment": ["35", "39"],
    "Beverage Manufacturing": ["11"],
    "Wholesale Metals and Minerals": ["46"],
    "Accommodation and Food Services": ["55", "56"],
    "Online Media": ["63", "59"],
    "Retail Luxury Goods and Jewelry": ["47"],
    "Animation": ["59"],
    "Renewable Energy Semiconductor Manufacturing": ["27", "26"],
    "Industrial Automation": ["28", "33"],
    "Glass, Ceramics and Concrete Manufacturing": ["23"],
    "Medical Device": ["32"],
    "Packaging and Containers Manufacturing": ["22", "17"],
    "Hotels and Motels": ["55"],
    "Semiconductors": ["26"],
    "Automation Machinery Manufacturing": ["28"],
    "Wholesale Appliances, Electrical, and Electronics": ["46"],
    "Commercial Real Estate": ["68"],
    "Government Relations Services": ["70"],
    "Wine & Spirits": ["11"],
    "Bed-and-Breakfasts, Hostels, Homestays": ["55"],
    "Mechanical Or Industrial Engineering": ["71", "28"],
    "Horticulture": ["01"],
    "Transportation/Trucking/Railroad": ["49"],
    "Packaging & Containers": ["22"],
    "Food Production": ["10"],
    "Sporting Goods": ["32"],
    "Wholesale Hardware, Plumbing, Heating Equipment": ["46"],
    "Aviation & Aerospace": ["30", "51"],
    "Design": ["74"],
    "Tobacco": ["12"],
    "Warehousing": ["52"],
    "Philanthropy": ["88"],
    "Information Technology & Services": ["62"],
    "Government Relations": ["70"],
    "Research": ["72"],
    "Computer Networking": ["61", "62"],
    "Wholesale Machinery": ["46"],
    "Computer Hardware": ["26"],
    "Caterers": ["56"],
    "Maritime": ["50"],
    "Entertainment": ["90", "59"],
    "Mobile Food Services": ["56"],
    "Biotechnology": ["72", "21"],
    "Paper & Forest Products": ["17"],
    "Renewable Energy Power Generation": ["35"],
    "Bars, Taverns, and Nightclubs": ["56"],
    "Renewable Energy Equipment Manufacturing": ["27", "28"],
    "Engineering Services": ["71"],
    "Services for Renewable Energy": ["35", "43"],
    "Digital Accessibility Services": ["62"],
    "Accessible Hardware Manufacturing": ["26"],
    "Accessible Architecture and Design": ["71"],
    "Robot Manufacturing": ["28"],
    "Robotics Engineering": ["71", "28"],
    "Repair and Maintenance": ["95", "33"],
    "Surveying and Mapping Services": ["71"],
    "Vehicle Repair and Maintenance": ["45"],
    "Retail Pharmacies": ["47"],
    "Climate Technology Product Manufacturing": ["27"],
    "Climate Data and Analytics": ["63", "72"],
    "Alternative Fuel Vehicle Manufacturing": ["29"],
    "Wholesale Recyclable Materials": ["46", "38"],
    "Smart Meter Manufacturing": ["26"],
    "Fuel Cell Manufacturing": ["27"],
    "Wholesale Luxury Goods and Jewelry": ["46"],
    "Regenerative Design": ["71"],
    "Funeral Services": ["96"],
    "Death Care Services": ["96"],
    "Energy Technology": ["35", "72"],
    "Wholesale Paper Products": ["46"],
    "Electronic and Precision Equipment Maintenance": ["33", "95"],
    "Wholesale Drugs and Sundries": ["46"],
    "Wholesale Apparel and Sewing Supplies": ["46"],
    "Commercial and Industrial Machinery Maintenance": ["33"],
    "Farming, Ranching, Forestry": ["01", "02"],
    "Reupholstery and Furniture Repair": ["95"],
    "Wholesale Footwear": ["46"],
    "Wholesale Food and Beverage": ["46"],
    "Footwear and Leather Goods Repair": ["95"],
    "Personal and Laundry Services": ["96"],
    "Personal Care Services": ["96"],
    "Laundry and Drycleaning Services": ["96"],
    "Wholesale Raw Farm Products": ["46"],
    "Wholesale Chemical and Allied Products": ["46"],
    "Pet Services": ["96", "75"],
    "Wholesale Petroleum and Petroleum Products": ["46"],
    "Wholesale Alcoholic Beverages": ["46"],
    "Ranching and Fisheries": ["01", "03"],
    "Internet Marketplace Platforms": ["47", "63"],
    "Retail Motor Vehicles": ["45"],
    "Household Services": ["96", "81"],
    "Retail Furniture and Home Furnishings": ["47"],
    "Retail Appliances, Electrical, and Electronic Equipment": ["47"],
    "Forestry and Logging": ["02"],
    "Retail Building Materials and Garden Equipment": ["47"],
    "Health and Human Services": ["86", "88"],
    "Public Health": ["84", "86"],
    "Public Assistance Programs": ["84", "88"],
    "Food and Beverage Retail": ["47"],
    "Air, Water, and Waste Program Management": ["84", "39"],
    "Conservation Programs": ["84"],
    "Housing and Community Development": ["84", "68"],
    "Community Development and Urban Planning": ["84", "71"],
    "Economic Programs": ["84"],
    "Oil, Gas, and Mining": ["06", "07"],
    "Retail Health and Personal Care Products": ["47"],
    "Coal Mining": ["05"],
    "Military and International Affairs": ["84"],
    "Metal Ore Mining": ["07"],
    "Retail Gasoline": ["47"],
    "Operations Consulting": ["70"],
    "Nonmetallic Mineral Mining": ["08"],
    "Electric Power Transmission, Control, and Distribution": ["35"],
    "Electric Power Generation": ["35"],
    "Retail Musical Instruments": ["47"],
    "Hydroelectric Power Generation": ["35"],
    "Fossil Fuel Electric Power Generation": ["35"],
    "Retail Books and Printed News": ["47"],
    "Nuclear Electric Power Generation": ["35"],
    "Solar Electric Power Generation": ["35"],
    "Environmental Quality Programs": ["84", "39"],
    "Geothermal Electric Power Generation": ["35"],
    "Biomass Electric Power Generation": ["35"],
    "Natural Gas Distribution": ["35"],
    "Water, Waste, Steam, and Air Conditioning Services": ["36", "35"],
    "Retail Florists": ["47"],
    "Water Supply and Irrigation Systems": ["36"],
    "Retail Office Supplies and Gifts": ["47"],
    "Steam and Air-Conditioning Supply": ["35"],
    "Building Construction": ["41"],
    "Retail Recyclable Materials & Used Merchandise": ["47"],
    "Residential Building Construction": ["41"],
    "Data Infrastructure and Analytics": ["63", "62"],
    "Nonresidential Building Construction": ["41"],
    "Utility System Construction": ["42"],
    "Electrical Equipment Manufacturing": ["27"],
    "Online and Mail Order Retail": ["47"],
    "Subdivision of Land": ["68", "42"],
    "Highway, Street, and Bridge Construction": ["42"],
    "Specialty Trade Contractors": ["43"],
    "Building Structure and Exterior Contractors": ["43"],
    "Wind Electric Power Generation": ["35"],
    "Wineries": ["11"],
    "Building Equipment Contractors": ["43"],
    "Rail Transportation": ["49"],
    "Building Finishing Contractors": ["43"],
    "Ground Passenger Transportation": ["49"],
    "Urban Transit Services": ["49"],
    "Interurban and Rural Bus Services": ["49"],
    "Animal Feed Manufacturing": ["10"],
    "Taxi and Limousine Services": ["49"],
    "School and Employee Bus Services": ["49"],
    "Shuttles and Special Needs Transportation Services": ["49"],
    "Sugar and Confectionery Product Manufacturing": ["10"],
    "Pipeline Transportation": ["49"],
    "Fruit and Vegetable Preserves Manufacturing": ["10"],
    "Sightseeing Transportation": ["49", "79"],
    "Meat Products Manufacturing": ["10"],
    "Seafood Product Manufacturing": ["10"],
    "Baked Goods Manufacturing": ["10"],
    "Postal Services": ["53"],
    "Breweries": ["11"],
    "Distilleries": ["11"],
    "Technology, Information and Media": ["62", "58"],
    "Periodical Publishing": ["58"],
    "Book Publishing": ["58"],
    "Movies and Sound Recording": ["59"],
    "Apparel Manufacturing": ["14"],
    "Sound Recording": ["59"],
    "Sheet Music Publishing": ["58"],
    "Radio and Television Broadcasting": ["60"],
    "Fashion Accessories Manufacturing": ["15", "32"],
    "Leather Product Manufacturing": ["15"],
    "Cable and Satellite Programming": ["60"],
    "Telecommunications Carriers": ["61"],
    "Footwear Manufacturing": ["15"],
    "Women's Handbag Manufacturing": ["15"],
    "Satellite Telecommunications": ["61"],
    "Credit Intermediation": ["64"],
    "Savings Institutions": ["64"],
    "Loan Brokers": ["66"],
    "Oil and Coal Product Manufacturing": ["19"],
    "Securities and Commodity Exchanges": ["66"],
    "Chemical Raw Materials Manufacturing": ["20"],
    "Investment Advice": ["66"],
    "Insurance Carriers": ["65"],
    "Artificial Rubber and Synthetic Fiber Manufacturing": ["20"],
    "Agricultural Chemical Manufacturing": ["20"],
    "Insurance Agencies and Brokerages": ["66"],
    "Claims Adjusting, Actuarial Services": ["66"],
    "Funds and Trusts": ["64", "66"],
    "Insurance and Employee Benefit Funds": ["65"],
    "Pension Funds": ["65"],
    "Paint, Coating, and Adhesive Manufacturing": ["20"],
    "Trusts and Estates": ["64"],
    "Soap and Cleaning Product Manufacturing": ["20"],
    "Real Estate and Equipment Rental Services": ["68", "77"],
    "Leasing Residential Real Estate": ["68"],
    "Plastics and Rubber Product Manufacturing": ["22"],
    "Real Estate Agents and Brokers": ["68"],
    "Equipment Rental Services": ["77"],
    "Consumer Goods Rental": ["77"],
    "Rubber Products Manufacturing": ["22"],
    "Clay and Refractory Products Manufacturing": ["23"],
    "Commercial and Industrial Equipment Rental": ["77"],
    "Glass Product Manufacturing": ["23"],
    "Wood Product Manufacturing": ["16"],
    "Professional Services": ["70"],
    "Lime and Gypsum Products Manufacturing": ["23"],
    "Abrasives and Nonmetallic Minerals Manufacturing": ["23"],
    "Primary Metal Manufacturing": ["24"],
    "IT System Design Services": ["62"],
    "Marketing Services": ["73"],
    "Fabricated Metal Products": ["25"],
    "Cutlery and Handtool Manufacturing": ["25"],
    "Architectural and Structural Metal Manufacturing": ["25"],
    "Boilers, Tanks, and Shipping Container Manufacturing": ["25"],
    "Construction Hardware Manufacturing": ["25"],
    "Spring and Wire Product Manufacturing": ["25"],
    "Turned Products and Fastener Manufacturing": ["25"],
    "Holding Companies": ["64", "70"],
    "Metal Treatments": ["25"],
    "Industry Associations": ["94"],
    "Landscaping Services": ["81"],
    "Metal Valve, Ball, and Roller Manufacturing": ["28"],
    "Professional Organizations": ["94"],
    "Administrative and Support Services": ["82"],
    "Office Administration": ["82"],
    "Executive Search Services": ["78"],
    "Agriculture, Construction, Mining Machinery Manufacturing": ["28"],
    "Temporary Help Services": ["78"],
    "Telephone Call Centers": ["82"],
    "Collection Agencies": ["82"],
    "Commercial and Service Industry Machinery Manufacturing": ["28"],
    "HVAC and Refrigeration Equipment Manufacturing": ["28"],
    "Metalworking Machinery Manufacturing": ["28"],
    "Security Guards and Patrol Services": ["80"],
    "Security Systems Services": ["80"],
    "Engines and Power Transmission Equipment Manufacturing": ["28"],
    "Janitorial Services": ["81"],
    "Waste Collection": ["38"],
    "Waste Treatment and Disposal": ["38"],
    "Communications Equipment Manufacturing": ["26"],
    "Audio and Video Equipment Manufacturing": ["26"],
    "Education": ["85"],
    "Measuring and Control Instrument Manufacturing": ["26"],
    "Secretarial Schools": ["85"],
    "Magnetic and Optical Media Manufacturing": ["26"],
    "Technical and Vocational Training": ["85"],
    "Cosmetology and Barber Schools": ["85"],
    "Flight Training": ["85"],
    "Electric Lighting Equipment Manufacturing": ["27"],
    "Public Works": ["42", "84"],
    "Fine Arts Schools": ["85"],
    "Parts Distribution": ["45", "46"],
    "Sports and Recreation Instruction": ["85", "93"],
    "Household Appliance Manufacturing": ["27"],
    "Language Schools": ["85"],
    "Physicians": ["86"],
    "Courts of Law": ["84"],
    "Correctional Institutions": ["84"],
    "Dentists": ["86"],
    "Fire Protection": ["84"],
}


def all_industries() -> list[str]:
    return sorted(INDUSTRY_SIC.keys())


def sic_for_industry(name: str) -> list[str]:
    return INDUSTRY_SIC.get(name, [])
