"""Regenerate billing.gen.ts for the journey function.

The journey cannot read the hub at runtime, so it carries a generated copy of
the two things it must never hand-type (handoff 23 Sep 2026):

  * prices   -- _Hub/pricing/tmh_pricing_catalogue.json (AUDIT_UK,
                AUDIT_WORLDWIDE, CONSULT_CLEARANCE: RRP / Discounted / Baseline)
  * codes    -- temmy-access/tmh_billing.py (LINES['clearance_audit'],
                FORBIDDEN_ON_INVOICE)

Re-run after either source changes, then redeploy the function:

    python3 gen_billing.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MOAT = HERE.parents[3]                       # .../TMH Braudit MOAT
_CANDIDATES = [MOAT.parent / "_Hub" / "pricing" / "tmh_pricing_catalogue.json",
               MOAT.parent / "TMH HQ" / "_Hub" / "pricing" / "tmh_pricing_catalogue.json"]
CATALOGUE = next((p for p in _CANDIDATES if p.exists()), _CANDIDATES[0])
sys.path.insert(0, str(MOAT / "temmy-access"))
import tmh_billing  # noqa: E402

SKUS = {  # catalogue SKU -> Zoho Product_Code pair (domestic, international)
    "AUDIT_UK": ("UKTM-AUD-UK-DOM", "UKTM-AUD-UK-INTL"),
    "AUDIT_WORLDWIDE": ("UKTM-AUD-WW-DOM", "UKTM-AUD-WW-INTL"),
    "CONSULT_CLEARANCE": ("UKTM-CONS-DOM", "UKTM-CONS-INTL"),
}


def main() -> None:
    cat = {c["sku"]: c for c in json.loads(CATALOGUE.read_text())["catalogue"] if "sku" in c}
    out = {}
    for sku, (dom, intl) in SKUS.items():
        c = cat[sku]
        out[sku] = {"name": c["name"], "unit": c["unit"],
                    "rrp": c["price_standard"], "discounted": c["price_discounted"],
                    "baseline": c["price_baseline"],
                    "product_code_dom": dom, "product_code_intl": intl}
    uk, nonuk, _ = tmh_billing.LINES["clearance_audit"]
    codes = {"uk": uk, "nonuk": nonuk, "tax_uk": tmh_billing.VAT20, "tax_nonuk": tmh_billing.NOVAT,
             "forbidden": sorted(tmh_billing.FORBIDDEN_ON_INVOICE)}
    ts = ("// GENERATED by gen_billing.py -- do not edit by hand.\n"
          "// Sources: _Hub/pricing/tmh_pricing_catalogue.json, temmy-access/tmh_billing.py\n"
          f"export const CATALOGUE = {json.dumps(out, indent=2)} as const;\n\n"
          f"export const BILLING_CODES = {json.dumps(codes, indent=2)} as const;\n")
    (HERE / "billing.gen.ts").write_text(ts)
    print(ts)


if __name__ == "__main__":
    main()
